# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Neurolog' do

pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'Eureka', '~> 1.4’
pod 'SimpleAlert'
pod 'Signature'
pod 'Agrume', :git => 'https://github.com/JanGorman/Agrume.git'
pod 'Charts'
pod 'UIAlertController+Blocks'
end


target 'NeurologTests' do

end

target 'NeurologUITests' do

end

