# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Neurolog' do

pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'Eureka', '~> 1.4'
end


target 'NeurologTests' do

end

target 'NeurologUITests' do

end

